site_name: MkDocs Entangled plugin
site_url: https://entangled.github.io/mkdocs-plugin
repo_url: https://github.com/entangled/mkdocs-plugin

plugins:
  - entangled

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
