site_name: MkDocs Entangled plugin
site_url: https://entangled.github.io/mkdocs-plugin
repo_url: https://github.com/entangled/mkdocs-plugin

plugins:
  - entangled

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

theme:
  name: material
