# ~/~ begin <<docs/setup.md#examples/entangled.toml>>[init]
version = "2.0"
watch_list = ["docs/**/*.md"]
hooks = ["repl"]

# ~/~ begin <<docs/setup.md#repl-config>>[init]
[hook.repl.config.Lua]
command = "lua"
first_prompt = "> "
change_prompt = '_PROMPT = "{key}> "; _PROMPT2 = "{key}+ "'
prompt = "{key}> "
continuation_prompt = "{key}\\+ "
strip_ansi = true
# ~/~ end
# ~/~ end
